import { UserRole } from '../../domain/models/user.model';

export const ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  [UserRole.SUPER_ADMIN]: ['*'],
  [UserRole.ADMIN]: [
    'dashboard.view',
    'reports.view',
    'activity.view',
    'settings.view',
    'rbac.manage',
    'rbac.permissions.view',
    'rbac.roles.view',
    'rbac.users.view',
    'rbac.role_permissions.view',
    'rbac.user_roles.view',
    'rbac.user_permissions.view',
    'users.view',
    'users.create',
    'users.edit',
    'users.delete',
    'alumni.view',
    'alumni.create',
    'alumni.edit',
    'alumni.delete',
    'events.view',
    'events.create',
    'events.edit',
    'events.delete',
    'events.rsvp',
    'events.view_rsvps',
    'jobs.view',
    'jobs.create',
    'jobs.edit',
    'jobs.delete',
    'jobs.apply',
    'jobs.view_applications',
    'notices.view',
    'notices.manage_categories',
    'notices.create',
    'notices.edit',
    'notices.delete',
    'elections.view',
    'elections.manage',
    'elections.vote',
    'elections.results',
    'cms.view',
    'cms.manage',
    'alumni.profile.edit',
  ],
  [UserRole.EVENT_MANAGER]: [
    'dashboard.view',
    'reports.view',
    'events.view',
    'events.create',
    'events.edit',
    'events.rsvp',
    'events.view_rsvps',
    'jobs.view',
    'notices.view',
    'alumni.view',
  ],
  [UserRole.ELECTION_MANAGER]: [
    'dashboard.view',
    'reports.view',
    'elections.view',
    'elections.manage',
    'elections.vote',
    'elections.results',
    'notices.view',
    'alumni.view',
  ],
  [UserRole.ALUMNI]: [
    'dashboard.view',
    'reports.view',
    'alumni.view',
    'alumni.profile.edit',
    'events.view',
    'events.rsvp',
    'jobs.view',
    'jobs.apply',
    'notices.view',
    'elections.view',
    'elections.vote',
    'elections.results',
    'cms.view',
  ],
  [UserRole.MANAGER]: ['dashboard.view', 'reports.view'],
  [UserRole.USER]: ['dashboard.view'],
};

export const ROLE_LABELS: Partial<Record<UserRole, string>> = {
  [UserRole.SUPER_ADMIN]: 'Alumni Super Admin',
  [UserRole.ADMIN]: 'Alumni Admin',
  [UserRole.EVENT_MANAGER]: 'Event Coordinator',
  [UserRole.ELECTION_MANAGER]: 'Election Coordinator',
  [UserRole.ALUMNI]: 'Alumni Member',
};

export const getPermissionsForRole = (role: UserRole): string[] => ROLE_PERMISSIONS[role] || [];
