"""Schemas module initialization."""
from app.schemas.auth import (
    TokenResponse,
    SendOTPRequest,
    VerifyOTPRequest,
    SetPasswordRequest,
    LoginRequest,
    RefreshTokenRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    UserResponse,
    CurrentUserResponse,
)
from app.schemas.alumni import (
    AlumniCreateRequest,
    AlumniUpdateRequest,
    AlumniResponse,
    AlumniListResponse,
    AlumniSearchRequest,
    PaginatedAlumniResponse,
)
from app.schemas.event import (
    EventCreateRequest,
    EventUpdateRequest,
    EventResponse,
    EventListResponse,
    EventRSVPRequest,
    EventRSVPResponse,
    PaginatedEventResponse,
)
from app.schemas.job import (
    JobCreateRequest,
    JobUpdateRequest,
    JobResponse,
    JobListResponse,
    JobApplicationRequest,
    JobApplicationResponse,
    PaginatedJobResponse,
)
from app.schemas.notice import (
    NoticeCategoryRequest,
    NoticeCategoryResponse,
    NoticeCreateRequest,
    NoticeUpdateRequest,
    NoticeResponse,
    NoticeListResponse,
    PaginatedNoticeResponse,
)
from app.schemas.election import (
    ElectionCreateRequest,
    ElectionResponse,
    PositionCreateRequest,
    PositionResponse,
    CandidateCreateRequest,
    CandidateResponse,
    CandidateWithVotesResponse,
    VoteRequest,
    VotingResultResponse,
    ElectionResultResponse,
)
from app.schemas.cms import (
    PageCreateRequest,
    PageUpdateRequest,
    PageResponse,
    SliderCreateRequest,
    SliderUpdateRequest,
    SliderResponse,
    CommitteeCreateRequest,
    CommitteeUpdateRequest,
    CommitteeResponse,
    GalleryCreateRequest,
    GalleryResponse,
    ContactInfoResponse,
)

__all__ = [
    # Auth
    "TokenResponse",
    "SendOTPRequest",
    "VerifyOTPRequest",
    "SetPasswordRequest",
    "LoginRequest",
    "RefreshTokenRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "UserResponse",
    "CurrentUserResponse",
    # Alumni
    "AlumniCreateRequest",
    "AlumniUpdateRequest",
    "AlumniResponse",
    "AlumniListResponse",
    "AlumniSearchRequest",
    "PaginatedAlumniResponse",
    # Events
    "EventCreateRequest",
    "EventUpdateRequest",
    "EventResponse",
    "EventListResponse",
    "EventRSVPRequest",
    "EventRSVPResponse",
    "PaginatedEventResponse",
    # Jobs
    "JobCreateRequest",
    "JobUpdateRequest",
    "JobResponse",
    "JobListResponse",
    "JobApplicationRequest",
    "JobApplicationResponse",
    "PaginatedJobResponse",
    # Notices
    "NoticeCategoryRequest",
    "NoticeCategoryResponse",
    "NoticeCreateRequest",
    "NoticeUpdateRequest",
    "NoticeResponse",
    "NoticeListResponse",
    "PaginatedNoticeResponse",
    # Elections
    "ElectionCreateRequest",
    "ElectionResponse",
    "PositionCreateRequest",
    "PositionResponse",
    "CandidateCreateRequest",
    "CandidateResponse",
    "CandidateWithVotesResponse",
    "VoteRequest",
    "VotingResultResponse",
    "ElectionResultResponse",
    # CMS
    "PageCreateRequest",
    "PageUpdateRequest",
    "PageResponse",
    "SliderCreateRequest",
    "SliderUpdateRequest",
    "SliderResponse",
    "CommitteeCreateRequest",
    "CommitteeUpdateRequest",
    "CommitteeResponse",
    "GalleryCreateRequest",
    "GalleryResponse",
    "ContactInfoResponse",
]
